### ISSUE TITLE
Sequence number & export time order switched

### ISSUE THREAD

**Issue by brettdh** [britram/python-ipfix#15]
When I send IPFIX constructed with `MessageBuffer.to_bytes`, I see the following in wireshark:
![image](https://cloud.githubusercontent.com/assets/91550/4597461/3019801a-50ae-11e4-97a5-e48ea9f8e1a5.png)
The value recorded as the seqno is actually the export timestamp, and vice versa.  I found the relevant code in message.py, in `MessageBuffer.to_bytes`:

```
        # Update message header in buffer
        _msghdr_st.pack_into(self.mbuf, 0, 10, self.length,
                             self.sequence, self.export_epoch, self.odid)
```

As expected, `sequence` precedes `export_epoch` in the `pack_into` call.  This is also the case with `read_message`:

```
(version, self.length, self.sequence, self.export_epoch, self.odid) = \
                _msghdr_st.unpack_from(self.mbuf, 0)
```

Wireshark's expectations match [RFC 7011](http://tools.ietf.org/html/rfc7011#section-3.1).

I'm fixing this (and adding a test) in my 2.7 branch (private for the moment). I'd be happy to cherry-pick those changes into a pull request when they're done -- or I can hand that off for now; either way is fine.

**Comment by nickbroon** [comment]
It would definitely be good to see the 0.9.7 release merged to the master branch.
