### ISSUE TITLE
Enable Travis CI?

### ISSUE THREAD

**Issue by brettdh** [britram/python-ipfix#23]
When I was developing #2, I added a `.travis-ci.yml` file for running the tests on Python 2.7, 3.3, and 3.4. However, it's only enabled on my fork. If you want to have this, you just need to go here, sign in with GitHub, and enable it:

https://travis-ci.org/britram/python-ipfix

If not, I'd suggest removing the config file.

**Comment by britram** [comment]
Done, thanks for the pointer (and the travis configuration!)
